Host windows-10
    HostName localhost
    User Quickemu
    Port 22220

    WarnWeakCrypto no
    PreferredAuthentications password
    PubkeyAuthentication no

    RequestTTY yes
    RemoteCommand C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\powershell.exe
